#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail
IFS=$'\n\t'
trap ctrl_c 2
function ctrl_c () {
		echo
		echo -e "$G[*]$W Contacta https://t.me/CesarGray"
	}
function Cesar {

echo $(clear)
echo
echo
echo 
sleep 2
echo -e "$G[*]$W Se ha instalando con exito..."
echo -e "$G[*]$W Contactame https://t.me/CesarGray"
echo -e "$G[*]$W Recompile by @CesarHackGray"
echo
echo
exit

function banner {


	echo $(clear)
echo
echo
sleep 2
echo -e "$G[*]$W Instalando openjdk....."
echo
echo
echo
sleep 3

echo $(clear)
echo
echo
echo
sleep 2
echo
echo -e "$G[*]$W Brindando modos a cada uno en openjdk"
sleep 4
chmod 700 ~/java/openjdk/*
chmod 700 ~/java/openjdk/bin/*
chmod 700 ~/java/openjdk/lib/*
chmod 700 ~/java/openjdk/.lib/*
chmod 700 ~/java/.Gray/*

apktool=$(find $PREFIX/bin -name "apktool")
java=$(find $PREFIX/bin -name "java")

if [ -e /data/data/com.termux/files/home/metasploit-framework ]; then

msf=$(find $HOME -name "metasploit-framework" -type d)

fi
if [ -e /data/data/com.termux/files/usr/opt/metasploit-framework ]; then
msf=$(find $PREFIX/opt -name "metasploit-framework" -type d)
fi

sleep 3




arch=`dpkg --print-architecture`

	if [ $arch = "aarch64" -o $arch = "arm64" ] ; then
		sleep 3
		echo $(clear)
		echo
		sleep 2
		echo
		echo
		printf "$G[*]$W Espera se esta instalando jdk-8..."
		sleep 1
		echo
		echo $(wget https://github.com/ivam3/java/releases/download/v8/jdk8_aarch64.tar.gz)
		sleep 1
		printf "$G[*]$W Moviendo jdk en el sistema..."
		mv jdk8_aarch64.tar.gz $PREFIX/share
		sleep 1
		printf "$G[*]$W Extrayendo ...$reset\n"
		cd $PREFIX/share
		tar -xhf jdk8_aarch64.tar.gz
		sleep 1
		printf "$G[*]$W Copiando  ...$reset\n"
		mv bin/* $PREFIX/bin/
		rm -rf $PREFIX/share/bin
			if [ ! -z $apktool ]; then
				rm $PREFIX/bin/apktool
			fi
		cp $HOME/java/.Gray/apktool $PREFIX/bin/
		cp $HOME/java/openjdk/apktool_jar/apktool_2.3.4.jar $PREFIX/var/spool/apktool.jar
		cp $HOME/java/openjdk/lib/libc++_shared.so $PREFIX/share/glib/
		chmod 711 $PREFIX/share/jdk8/man/ja_JP.UTF-8/man1/*
	
		sleep 1
		echo
if [ -e /data/data/com.termux/files/usr/share/jdk8/bin/java ]; then
chmod 700 /data/data/com.termux/files/usr/share/jdk8/bin/java
		fi
		Cesar

	elif [ $arch = "armhf" -o $arch = "armv7l" ]; then
		sleep 3
		echo
		echo $(clear)
		echo
		sleep 2
		echo
		printf "$G[*]$W Espera se esta instalando jdk-8....\n"
		sleep 1
		echo $(wget https://github.com/ivam3/java/releases/download/v8/jdk8_aarch64.tar.gz)
		sleep 1
		printf "$G[*]$W Moviendo jdk a bin ...$reset\n"
		mv jdk8_arm.tar.gz $PREFIX/share
		echo
		sleep 1
		printf "$G[*]$W Extrayendo....$reset\n"
		cd $PREFIX/share
		tar -xhf jdk8_arm.tar.gz
		sleep 1
		printf "$G[*]$W Moviendo .....\n"
		mv bin/* $PREFIX/bin
		rm -rf $PREFIX/share/bin
			if [ ! -z $apktool ]; then
				rm $PREFIX/bin/apktool
			fi
		cp $HOME/java/.Gray/apktool $PREFIX/bin/
		cp $HOME/java/openjdk/apktool_jar/apktool_2.3.4.jar $PREFIX/var/spool/apktool.jar
		cp $HOME/java/openjdk/lib/libc++_shared.so $PREFIX/share/glib/
		chmod 711 $PREFIX/share/jdk8/man/ja_JP.UTF-8/man1/*
		
		sleep 1
		echo
if [ -e /data/data/com.termux/files/usr/share/jdk8/bin/java ]; then
chmod 700 /data/data/com.termux/files/usr/share/jdk8/bin/java
fi
Cesar
	elif [ $arch = "arm" -o $arch = "i868" ]; then
		sleep 3
		echo
		echo $(clear)
		echo
		echo
		echo
		sleep 2
		printf "$G[*]$W Espera se esta instalando jdk-...\n"
		sleep 1
		echo $(wget https://github.com/ivam3/java/releases/download/v8-151/jdk8_arm.tar.gz)
		sleep 1
		printf "$G[*]$W Moviendo jdk en el sistema...$reset\n"
		mv jdk8_arm.tar.gz $PREFIX/share
		sleep 1
		printf "$G[*]$W Extrayendo ...$reset\n"
		cd $PREFIX/share
		tar -xhf jdk8_arm.tar.gz
		sleep 1
		printf "$G[*]$W Moviendo java a bin....\n"
			if [ ! -z $java ]; then
				rm $java
			fi
			if [ ! -z $apktool ]; then
				rm $apktool
			fi
			cp $HOME/java/.Gray/apktool $PREFIX/bin/
			cp $HOME/java/openjdk/apktool_jar/apktool-2.2.2.jar $PREFIX/var/spool/apktool.jar
			cp $HOME/java/openjdk/lib/libc++_shared.so $PREFIX/share/glib/
			mv bin/* $PREFIX/bin
			rm -rf $PREFIX/share/bin
			chmod 711 $PREFIX/share/jdk8/man/ja_JP.UTF-8/man1/*
			mv $PREFIX/share/jdk8/bin/java $PREFIX/share/jdk8/bin/java.O
			cp $HOME/java/openjdk/bin/java $PREFIX/share/jdk8/bin/
if [ -e /data/data/com.termux/files/usr/share/jdk8/bin/java ]; then
chmod 700 /data/data/com.termux/files/usr/share/jdk8/bin/java
fi
Cesar
		
			sleep 1
	else
	
		printf "$G[$R!$G]$W Error tu artitectura no es compatinle lo siento"
		exit
		sleep 5
	fi
}
banner
